// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBs9n3TSnkYeKzwBj6oHWh5EK9LHZ9T-QE',
    appId: '1:393808700260:web:62ec2fa8a800f03cc29071',
    messagingSenderId: '393808700260',
    projectId: 'eurofarma-e0432',
    authDomain: 'eurofarma-e0432.firebaseapp.com',
    databaseURL: 'https://eurofarma-e0432-default-rtdb.firebaseio.com',
    storageBucket: 'eurofarma-e0432.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDoRoSWTuRY_g1_fnmwC4TvvfHNOtifv0o',
    appId: '1:393808700260:android:281eae4337be7db9c29071',
    messagingSenderId: '393808700260',
    projectId: 'eurofarma-e0432',
    databaseURL: 'https://eurofarma-e0432-default-rtdb.firebaseio.com',
    storageBucket: 'eurofarma-e0432.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB0PKHSc2sbcjPkwCLzZ6yCw8SK9SL06Mc',
    appId: '1:393808700260:ios:3fc7bfeb1adf8d14c29071',
    messagingSenderId: '393808700260',
    projectId: 'eurofarma-e0432',
    databaseURL: 'https://eurofarma-e0432-default-rtdb.firebaseio.com',
    storageBucket: 'eurofarma-e0432.firebasestorage.app',
    iosBundleId: 'com.example.bd',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB0PKHSc2sbcjPkwCLzZ6yCw8SK9SL06Mc',
    appId: '1:393808700260:ios:3fc7bfeb1adf8d14c29071',
    messagingSenderId: '393808700260',
    projectId: 'eurofarma-e0432',
    databaseURL: 'https://eurofarma-e0432-default-rtdb.firebaseio.com',
    storageBucket: 'eurofarma-e0432.firebasestorage.app',
    iosBundleId: 'com.example.bd',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBs9n3TSnkYeKzwBj6oHWh5EK9LHZ9T-QE',
    appId: '1:393808700260:web:d559c6128f747da7c29071',
    messagingSenderId: '393808700260',
    projectId: 'eurofarma-e0432',
    authDomain: 'eurofarma-e0432.firebaseapp.com',
    databaseURL: 'https://eurofarma-e0432-default-rtdb.firebaseio.com',
    storageBucket: 'eurofarma-e0432.firebasestorage.app',
  );
}
